apiVersion: v2
appVersion: 1.4.1
dependencies:
- condition: cassandra.enabled
  name: cassandra
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  version: 0.14.3
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 11.0.4
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.6.2
- condition: kafka.enabled
  name: kafka
  repository: https://charts.bitnami.com/bitnami
  version: 7.2.9
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 5.0.10
description: Temporal is a distributed, scalable, durable, and highly available orchestration
  engine to execute asynchronous long-running business logic in a scalable and resilient
  way.
home: https://temporal.io/
keywords:
- temporal
- workflow
- orchestration
maintainers:
- name: Temporal Technologies Inc.
  url: https://temporal.io/
name: temporal
sources:
- https://github.com/temporalio/temporal
type: application
version: 0.2.0
